name: Export de métricas

on: 
  push:
    branches: [master]
    tags:
      - "v*"
  pull_request:
    branches:
      - master
      - devel
    types: [ closed ]

jobs:
  release:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'NOT RELEASE') == false
    runs-on: "ubuntu-latest"
    environment: actions
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install dotenv
        run: pip install python-dotenv packaging pandas
          
      - name: Cria arquivo .env
        run: |
          touch ./sonar_scripts/.env
          echo GITHUB_TOKEN=${{secrets.PERSONAL_TOKEN}} >> ./sonar_scripts/.env
          echo RELEASE_MAJOR=${{ contains(github.event.pull_request.labels.*.name, 'MAJOR RELEASE') }} >> ./sonar_scripts/.env
          echo RELEASE_MINOR=${{ contains(github.event.pull_request.labels.*.name, 'MINOR RELEASE') }} >> ./sonar_scripts/.env
          echo RELEASE_FIX=${{ contains(github.event.pull_request.labels.*.name, 'FIX RELEASE') }} >> ./sonar_scripts/.env
          echo DEVELOP=${{ contains(github.event.pull_request.labels.*.name, 'DEVELOP') }} >> ./sonar_scripts/.env
          echo REPO=${{ github.event.repository.name }} >> ./sonar_scripts/.env

      - name: Criar diretório
        run: mkdir -p analytics-raw-data

      - name: Coletar métricas no SonarCloud
        run: python ./sonar_scripts/parser.py

      - name: Envia métricas para repo de Doc
        run: |
          git config --global user.email "${{secrets.GIT}}"
          git config --global user.name "${{secrets.GIT}}"
          git clone --single-branch --branch main "https://x-access-token:${{secrets.PERSONAL_TOKEN}}@github.com/fga-eps-mds/2024.2-SENTINELA-DOC" doc
          mkdir -p doc/analytics-raw-data
          cp -R analytics-raw-data/*.json doc/analytics-raw-data
          cd doc
          git add .
          git commit -m "Adicionando métricas do repositório ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push